[env:custom_build]
extends = env:esp32s3dev_8MB_PSRAM_opi
build_flags = ${env:esp32s3dev_8MB_PSRAM_opi.build_flags} -D MIC_LOGGER -D WLED_AP_SSID_UNIQUE -D WLED_ENABLE_PIXART -D DEFAULT_LED_TYPE= -D CLIENT_SSID='"gank"' -D CLIENT_PASS='"31313131"' -D USERMOD_DHT -D USERMOD_DHT_CELSIUS -D USERMOD_FOUR_LINE_DISPLAY -D USERMOD_SENSORSTOMQTT -D USERMOD_PIRSWITCH
lib_deps = 
  ${env:esp32s3dev_8MB_PSRAM_opi.lib_deps}
  https://github.com/alwynallan/DHT_nonblocking
  olikraus/U8g2 @ ^2.28.8
  adafruit/Adafruit BMP280 Library @ 2.1.0
  adafruit/Adafruit CCS811 Library @ 1.0.4
  adafruit/Adafruit Si7021 Library @ 1.4.0
  adafruit/Adafruit Unified Sensor
